---
title: "R Notebook"
output: html_notebook
---



```{r}
library(data.table)

library(lubridate)

COLS_FOR_TABLE <- c(
  "cases",
  "cum_tests",
  "tested",
  "curr_hospi",
  "cum_hospi",
  "curr_icu",
  "cum_icu",
  "curr_respi",
  "curr_ipc",
  "owid_cases",
  "owid_tested",
  "new_cases",
  "dead",
  "recovered",
  "owid_new_cases",
  "owid_dead",
  "owid_new_dead",
  "owid_new_tested",
  "current_ecmo",
  "new_hospi",
  "new_out",
  "cured",
  "cum_out_hospi",
  "current_out_hospi",
  "cum_dead",
  "cum_tested",
  "curr_tested",
  "tested_positive",
  "infected",
  "curr_cases",
  "curr_dead",
  "new_cases_brutto",
  "new_dead",
  "new_cured",
  "curr_cured",
  "new_suspected_cases",
  "icu_with_al_one_case"
)

missing.cols <- setdiff(unique(DT$key), COLS_FOR_TABLE)

COLS_FOR_TABLE <- c(COLS_FOR_TABLE, missing.cols)

DT <- fread("https://checkercovid.s3.amazonaws.com/all_EU.csv")
# DT <-  fread('https://checkercovid.s3.amazonaws.com/all_EU_20200508_10:45:35.csv')
# DT <- fread("../../data/cleaned_data_archives/all_EU.csv")


DT$date <- ymd(DT$date)
DT$value <- as.numeric(DT$value)
DT <- DT[!is.na(value)]
DT <- DT[!is.na(key)]
DT <- unique(DT, by = c("date", "country", "key"))
DT <- DT[date <= Sys.Date()]
DT <- DT[order(date)]
DT$updated_on <- ymd_hms(DT$updated_on)
groupy <- DT[, .N, by = c("date", "key", "country")]

DT$key <- factor(DT$key, levels = COLS_FOR_TABLE)

DT <- DT[, .SD[.N], by = c("date", "key", "country")]
```


## dcast test
```{r}
DT.casted <-
  dcast(
    DT,
    date + country ~ key,
    fill = "no data",
    value.var = c("value")
  )[order(-date)]
```



```{r}
DT[, updated_on_dt := ymd(updated_on)]

DT.AT <- DT[country == "AT"][order(-date)]
unique(DT.AT$key)

groupy <- DT[, .N, by = .(country, date, key, updated_on_dt)]

DT <- unique(DT, by = c("date", "country", "key"))
```
```{r}


DT[, .N, by = .(country, date, key)][N > 1]
DT <- DT[!is.na(value)]
DT <- unique(DT, by = c("date", "country", "key", "updated_on"))
DT.casted <- dcast(DT, date + country + updated_on ~ key, fill = "no data", value.var = c("value"))[order(-date)][, ..COLS_FOR_TABLE]
```
```{r}
unique(DT$key)
```

```{r}

p <- ggplot(DT[], aes(date, value)) +
  geom_line(aes(color = key))
ggplotly(p)
```
